source 'http://rubygems.org'

gem 'rails', '3.0.9'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'haml'
gem 'jammit'  # Do we need this with guard?
gem 'json'
# gem 'barista' # Do we need this with guard?
# gem 'sass'    # Do we need this with guard?

# TODO: Split into separate test environments like :cucumber, :rpsec, etc etc!

# Adding cucumber, jasmine and rspec test suite
group :test, :development do
  
  # Test and dev prereqs
  gem 'capybara'
  gem 'database_cleaner'
  gem 'guard'
  gem 'cucumber'
  gem 'rspec'
  gem 'factory_girl_rails'
  gem 'launchy'    # So you can do Then show me the page  
  gem 'rb-fsevent' # To notify of fs changes in OSX
  
  # Giving problems..
    # gem 'rb-inotify' # To notify of fs changes in Linux
    # gem 'growl'  # Growl style notifications on OSX
    # gem 'growl_notify'  # Growl style notifications on OSX
    # gem 'libnotify'  # Growl style notifications on Linux

  # Back end guards
  gem 'spork', '~> 0.9.0.rc'
  gem 'guard-spork'  
  gem 'cucumber-rails'
  gem 'guard-cucumber'  
  gem 'rspec-rails'
  gem 'guard-rspec'
  
  # Front end guards
  gem 'guard-jammit'
  gem 'guard-coffeescript'
  gem 'therubyracer' # To use V8 as the CS compiler
  gem 'guard-sass' 
  gem 'jasmine'  
 # gem 'guard-jasmine-headless-webkit' 
end

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
