--- 
javascripts: 
  # COMMON STACK:
  hot_ping:
  - public/framework/js/dd_belatedpng.js
  power_extreme:
  - public/framework/js/html5shim.js
  prep_for_awesome: 
  - public/framework/js/modernizr-1.7.min.js
  awesome: 
  - public/framework/js/ender.js
  - public/framework/js/json2.js
  - public/framework/js/underscore.js
  - public/framework/js/x_backbone.js
  - public/framework/js/drag-drop.js  
  - public/javascripts/**/*.js 
  - app/views/**/*.jst
  
  # CUSTOM PACKAGES:
  prep_for_xipcraft_static_site:
  # xCheck.forJavaScript
  
  awesomeness_for_xipcraft_static_site:
    
stylesheets: 
  # COMMON STACK:
  gorgeous: 
  - public/stylesheets/**/*.css
  
  # CUSTOM PACKAGES:
  make_xipcraft_static_site_gorgeous:
  - public/stylesheets/xipcraft_static_site.css
  