---
embed_assets: on

javascripts: 
  # COMMON STACK:
  hot_ping:
  - public/framework/js/dd_belatedpng.js 
  
  prep_for_awesome: 
  - public/framework/js/modernizr-1.7.min.js
  - public/framework/js/respond.js
  
  awesome: 
  - public/framework/js/ender.js
  - public/framework/js/json2.js
  - public/framework/js/underscore.js
  - public/framework/js/x_backbone.js
  - public/framework/js/drag-drop.js  
  - public/javascripts/**/*.js 
  - app/views/**/*.jst
  
  # CUSTOM PACKAGES:
  prep_for_xipcraft_static_site:
  - public/javascripts/global_helpers/modernizr.xipcraft_static_site.js
  - public/javascripts/global_helpers/x_help.js
  - public/framework/js/respond.js
  
  awesomeness_for_xipcraft_static_site:
  - public/framework/js/bean.js
  - public/javascripts/sub_apps/xipcraft_static_site.js
    
stylesheets: 
  # COMMON STACK:
  gorgeous: 
  - public/stylesheets/**/*.css
  
  # CUSTOM PACKAGES:
  make_xipcraft_static_site_gorgeous:
  - public/stylesheets/xipcraft_static_site.css
  