--- 
javascripts: 
  hot_ping:
  - stage/framework/js/dd_belatedpng.js
  power_extreme:
  - stage/framework/js/html5shim.js
  prep_for_awesome: 
  - stage/framework/js/modernizr-1.7.min.js
  awesome: 
  - stage/framework/js/ender.js
  - stage/framework/js/json2.js
  - stage/framework/js/underscore.js
  - stage/framework/js/x_backbone.js
  - stage/framework/js/drag-drop.js
  - stage/bin/views/**/*.jst
  - stage/bin/**/*.js
  - stage/spec/**/*.js
  
stylesheets: 
  gorgeous: 
  - stage/framework/css/resets.css
  - stage/framework/css/common.css
  - stage/bin/styles/**/*.css
  - stage/framework/css/helpers.css
  - stage/framework/css/print.css